/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e044ca8d-bf9b-474d-aee8-c11a88b42509",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UC71p1e3w",
    "aws_user_pools_web_client_id": "3jf9c3rao0ttei3p42032pv2op",
    "oauth": {},
    "aws_user_files_s3_bucket": "thisorthatimagebucket143415-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://npqli6gacnf3zieu5lp7hlfz3i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t5nehd5cgrburmlbtp3b2r2wf4"
};


export default awsmobile;
