/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a9395a50-e5a8-4c1f-a3e6-90920949180b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DP1sgZ1FC",
    "aws_user_pools_client_id": "2h9vuffn6urim68lujmtsqfv1f",
    "oauth": {},
    "aws_user_files_s3_bucket": "thisorthatimagebucket143415-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://npqli6gacnf3zieu5lp7hlfz3i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t5nehd5cgrburmlbtp3b2r2wf4"
};


export default awsconfig;
